### ISSUE TITLE
Support for file uploads

### ISSUE THREAD

**Issue by LouisTrezzini** [allisson/python-simple-rest-client#1]
Hi, thanks for this library, it looks really promising!

Do you plan to add support for file uploads, similarly to what `unittest` provides?

```python
self.client.post("/upload", data={
    "name": "filename",
    "file": file
}, headers={})
```

Currently, when I try to do this, I get an error: 
> TypeError: <tempfile._TemporaryFileWrapper object at 0x7f797f6a44e0> is not JSON serializable

I'd be happy to write a PR if you'd review it.

**Comment by allisson** [comment]
Hi,

This is possible with version 0.4.0:
- https://github.com/allisson/python-simple-rest-client/blob/master/examples/async_file_upload.py
- https://github.com/allisson/python-simple-rest-client/blob/master/examples/file_upload.py
