### ISSUE TITLE
Authentication request

### ISSUE THREAD

**Issue by mkb79** [allisson/python-simple-rest-client#18]
Hi.
Thanks for your great work. It helps me a lot. 
But now I need some help. I‘d want to make a request to a api who needs a special form of authentication. In the request header I have to send a signature who is generated on every request.

Here is the copy for generating the signature. Input is an requests.Request.prepare() object.

    def prepare_request(request, adp_token, private_key):
        url_parsed = urlparse(request.url)
        path = url_parsed[2]
        query = url_parsed[4]
    
        url = path[:]
        if query:
            url += f"?{query}"
    
        headers = sign_request(
            url, request.method, request.body, adp_token, private_key
        )
        for item in headers:
            request.headers[item] = headers[item]
    
        return request

    def sign_request(url, method, body, adp_token, private_key):
        date = datetime.utcnow().isoformat("T") + "Z"
    
        data = f"{method}\n{url}\n{date}\n"
        if body:
            data += body
        data += "\n"
        data += adp_token
    
        key = rsa.PrivateKey.load_pkcs1(private_key)
        cipher = rsa.pkcs1.sign(data.encode(), key, "SHA-256")
        signed_encoded = base64.b64encode(cipher)
    
        signature = f"{signed_encoded.decode()}:{date}"
    
        return {
            "x-adp-token": adp_token,
            "x-adp-alg": "SHA256withRSA:1.0",
            "x-adp-signature": signature
        }

Is it possible to make such requests?

**Comment by mkb79** [comment]
This is the last line from sign_request

return {
        "x-adp-token": adp_token,
        "x-adp-alg": "SHA256withRSA:1.0",
        "x-adp-signature": signature
    }

**Comment by ronniehicks** [comment]
I believe it is. It's not very well documented, and I had to dig into the implementation to find it, but since this library uses the requests library, and aiohttp for async, behind the scenes you _should_ be able to create a custom auth handler for requests (example shown [here](http://docs.python-requests.org/en/master/user/advanced/#custom-authentication)) and pass that as a keyword arg to your http methods. Here's my 22:30 guess at what that might look like. I'll be working on a problem similar to this in the morning so will update once I get that working.

```python
from requests.auth import AuthBase

class SignatureAuth(AuthBase):
    def __init__(self, request):
        self.request = request

    def __call__(self, r):
        r.headers.update(self.sign_request_output))
        return r

# some predefined resource, SignedResource
signature_auth = SignatureAuth(request)

test_api = API(api_root_url="https://test.com")
test_api.add_resource(resource_name="test", resource_class=SignedResource)
test_api.retrieve(queryParam, auth=signature_auth)
```

**Comment by mkb79** [comment]
Hi. Thank you very much.

My solution looks like similar to yours. I have create a class who inherits from requests.auth.AuthBase.

Next I create a own Resource class who inherits from simple_rest_client.resource.Resource.

    class UserResource(Resource):
        actions = {
            'library': {'method': 'GET', 'url': "0.0/library/books"},
            'retrieve_wishlist': {'method': 'GET', 'url': '1.0/wishlist'},
            'add_to_wishlist': {'method': 'POST', 'url': '1.0/wishlist'},
            'remove_from_wishlist': {'method': 'DELETE', 'url': '1.0/wishlist/{}'}, 
    }
    
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.session.auth = PrivateKeyAuth(adp_token, private_key)
    
    
    default_header = {
            "Accept": 'application/json',
            'Content-Type': 'application/json'
        } 
    
    
    # create api instance
    audible_api = API(
        api_root_url='https://api.audible.de', headers=default_header,
        json_encode_body=True
    )
    # add events resource with EventResource
    audible_api.add_resource(resource_name='user', resource_class=UserResource)
    # show resource actions
    
    params = {'response_groups': 'product_desc'}
    response = audible_api.user.retrieve_wishlist(params=params)
